#!/bin/bash

# Instructions to setup call tables in Supabase
echo "=================================="
echo "Supabase Call Tables Setup"
echo "=================================="
echo ""
echo "To enable calling features, you need to run the SQL migration in your Supabase dashboard:"
echo ""
echo "1. Go to your Supabase project dashboard"
echo "2. Navigate to the SQL Editor"
echo "3. Click 'New Query'"
echo "4. Copy and paste the contents of CREATE_CALLS_TABLES.sql"
echo "5. Click 'Run' to execute the migration"
echo ""
echo "The migration will create:"
echo "  - calls table (for call records)"
echo "  - call_signals table (for WebRTC signaling)"
echo "  - Indexes for performance"
echo "  - Row Level Security policies"
echo "  - Automatic missed call detection"
echo ""
echo "File location: CREATE_CALLS_TABLES.sql"
echo "=================================="
